### PR TITLE
Translation to Spanish commit

### PR DESCRIPTION
**Pull request by lauracion**
will continue with partial translations until a final commit that completes de translation and PR 😄

### CODE REVIEW

**Comment by lauracion** [comment]
At the end of es.qmd there is this chunk of text:

> _This resource was generated as part of [CZI's EOSS](https://chanzuckerberg.com/eoss/) Community Calls during late 2024 with 
> [Organizational Mycology](https://orgmycology.com) facilitating discussions, gathering input, 
> and generating the final document. Participants in the calls, and open comment periods are 
> given co-authorship in alphabetical order by last name._  

Below this text:

>  

Adding the translation to the chunk here so the webpage of the Spanish version is fully in Spanish:

_Este recurso se creó a fines de 2024 como parte de las llamadas comunitarias del [EOSS de CZI](https://chanzuckerberg.com/eoss/) junto a [Organizational Mycology](https://orgmycology.com) facilitando debates, recopilando aportes y generando el documento final. Se otorga coautoría en orden alfabético por apellido a quienes participaron de la reunión o agregaron comentarios durante el período abierto._

**Comment by lauracion** [comment]
This translation is now ready to publish @jduckles 😄 

If feasible, it´d be great to mention somewhere that I did this translation on behalf of [MetaDocencia](https://www.metadocencia.org/en/)´s Contextualization Team.

**Comment by jduckles** [comment]
Something like:

"Laura Acion creó esta traducción en nombre del Equipo de Contextualización de [MetaDocencia](https://www.metadocencia.org/en/)."

**Comment by jduckles** [comment]
@lauracion Let me know if you like the Spanish and English versions of the mention of MetaDocencia. PR merged and translation is live! Thank you so much!

**Comment by lauracion** [comment]
Looks great! Thank you, Jonah! Happy Friday!

**Pull request merged**
